gcc-env:
  compiler:
      - toolchain: gcc
        spec: gcc@11
  unify: true
  specs:
  - cuda@11.8
  - osu-micro-benchmarks@5.9
  mpi:
    spec: cray-mpich
    gpu: cuda
  variants:
    - +mpi
    - +cuda
    - cuda_arch=80
# tools:
#   compiler:
#       - toolchain: gcc
#         spec: gcc@11
#   unify: true
#   specs:
#   - cmake
#   - python@3.10
